#!/bin/bash

cat > .gitignore << EOM
/node_modules
/public/hot
/public/storage
/storage/*.key
/vendor
/nbproject/*
.env
.env.development
.env.stage
.phpunit.result.cache
Homestead.json
Homestead.yaml
npm-debug.log
yarn-error.log
*.DS_Store
.scannerwork
.scannerwork/*
.htaccess
composer-setup.php
EOM
